export const GET_LIST_MOVIE = 'GET_LIST_MOVIE';
export const GET_SHOWING_MOVIE = 'GET_SHOWING_MOVIE';
export const GET_COMING_MOVIE = 'GET_COMING_MOVIE';
export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';

export const SET_MOVIE_INFO = 'SET_MOVIE_INFO';