
export const GROUP_ID_GP01 = 'GP01'
export const GET_LIST_THEATER = 'GET_LIST_THEATER';
export const GET_LIST_THEATER_SYSTEM = 'GET_LIST_THEATER_SYSTEM';
export const GET_LIST_SHOWTIME = 'GET_LIST_SHOWTIME'