

export const SET_BOOKING_TICKET_INFO = 'SET_BOOKING_TICKET_INFO';
export const BOOKING_CHAIR = 'BOOKING_CHAIR';
export const BOOKING_COMPLETE = 'BOOKING_COMPLETE';
export const CHANGE_TAB = 'CHANGE_TAB';
export const CHANGE_TAB_ACTIVE = 'CHANGE_TAB_ACTIVE';